C:\Users\Diana\Desktop\AAA\Python\HW5\task2>python -m pytest -v task2.py
================================================== test session starts ==================================================
platform win32 -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- C:\Users\Diana\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\Diana\Desktop\AAA\Python\HW5\task2
plugins: cov-3.0.0
collected 5 items

task2.py::test_decode[... --- ...-SOS] PASSED                                                                      [ 20%]
task2.py::test_decode[.... . .-.. .-.. --- -....- -.. .. .- -. .- -....- .... --- .-- -....- .- .-. . -....- -.-- --- ..- ..--..-HELLO-DIANA-HOW-ARE-YOU?] PASSED [ 40%]
task2.py::test_decode[... .. -- .--. .-.. . -....- - . ... - -....- .-- -....- .--. -.-- - . ... - .-.-.- .--. .- .-. .- -- . - .-. .. --.. .-SIMPLE-TEST-W-PYTEST.PARAMETRIZE] PASSED [ 60%]
task2.py::test_exception[hello-KeyError] PASSED                                                                    [ 80%]
task2.py::test_exception[123-AttributeError] PASSED                                                                [100%]

=================================================== 5 passed in 0.42s ===================================================
